name: CI

on:
  pull_request:

jobs:
  build:
    name: Building ${{ matrix.device }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          - ar-condicionado
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.2.0
      - uses: esphome/build-action@v1.1.0
        id: esphome-build
        with:
          yaml_file: leofig-${{ matrix.device }}.yaml
